//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public string IDMaGiamGia { get; set; }
        public string TenMaGiamGia { get; set; }
        public Nullable<System.DateTime> NgayBatDauGiamGia { get; set; }
        public Nullable<System.DateTime> NgayKetThucGiamGia { get; set; }
        public Nullable<int> SoTienGiam { get; set; }
    }
}
